### ISSUE TITLE
Unable to load the plugin

### ISSUE THREAD

**Issue by QSlotus** [yuko1101/CustomMailPlugin#1]
I'm using https://github.com/LunarCore-Mods/GameProvider along with CustomMailPlugin and have a mod loaded. 

When I launch it via `java @args.txt`, the mod is loaded successfully but an error occurs when loading the plugin:
```
[13:12:25] [ERROR] Unable to load plugins.
java.lang.RuntimeException: java.lang.NoSuchMethodException: io.github.yuko1101.custommail.CustomMailPlugin.<init>(emu.lunarcore.plugin.Plugin$Identifier,java.net.URLClassLoader,java.io.File,org.slf4j.Logger)
        at emu.lunarcore.plugin.PluginManager.lambda$loadPlugins$4(PluginManager.java:155)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at emu.lunarcore.plugin.PluginManager.loadPlugins(PluginManager.java:77)
        at emu.lunarcore.LunarCore.main(LunarCore.java:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.github.lunarcoremods.provider.services.LunarCoreGameProvider.launch(LunarCoreGameProvider.java:190)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at io.github.lunarcoremods.provider.Main.main(Main.java:11)
Caused by: java.lang.NoSuchMethodException: io.github.yuko1101.custommail.CustomMailPlugin.<init>(emu.lunarcore.plugin.Plugin$Identifier,java.net.URLClassLoader,java.io.File,org.slf4j.Logger)
        at java.base/java.lang.Class.getConstructor0(Class.java:3585)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
        at emu.lunarcore.plugin.PluginManager.lambda$loadPlugins$4(PluginManager.java:125)
        ... 10 common frames omitted
```
I am wondering if mods and plugins conflict when using gameprovider. If yes please tell me how to fix it. Thanks!

(I put `CustomMailPlugin` in the `plugins` folder and put the mods in the `mods` folder.)

**Comment by yuko1101** [comment]
It's a known issue with GameProvider. With GameProvider you cannot load any plugins.

You can patch it with [PluginManagerPatch](https://github.com/LunarCore-Mods/PluginManagerPatch) mod.

**Comment by QSlotus** [comment]
Thank you! The problem is solved.
